---

- name: install
  import_role:
    name: powo.archive
  vars:
    par_archive_destination_folder: "{{ pec_download_folder }}"
    par_archive_extraction_folder: "{{ _pec_item_install_folder }}"
    par_archive_url: "{{ _pec_item_download_url }}"
    par_archive_checksum: "{{ _pec_item_download_checksum }}"
