---
- name: Converge
  hosts: all
  serial: 1
  roles:
    - role: powo.eclipse
      pec_install_base_folder: "/tmp"
      pec_download_folder: "/tmp"
      pec_bundles:
        - url: copy:{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/eclipse-fake.tar.gz
          checksum: sha256:47b960891c4ca0d2f195afe7ba7932d82774a1ba9b97024e35c4cb6228415831
          desktop_name: Eclipse Oxygen (4.7.0)
