---
- name: Converge
  hosts: all
  serial: 1
  roles:
    - role: powo.eclipse
      pec_install_base_folder: "/tmp"
      pec_download_folder: "/tmp"
      pec_bundles:
        - url: copy:{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/eclipse-fake.tar.gz
          checksum: sha256:7713da412ea410370c1fd67e6589b2de792634aeea8f12f1d961d549e261438d
          desktop_name: Eclipse Oxygen (4.7.0)
